---
name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - '**.md'  # All markdown files in the repository
  release:
    types: [released]

jobs:
  deploy:
    if: github.repository_owner == 'GSA-TTS'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: GSA-TTS/identity-idva-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}
          space-suffix: "-public"

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.17.x"

      - name: Build Caddy
        run: ./install_caddy.sh && ./caddy version

      - name: Deploy Application
        run: cf push
          --var ENVIRONMENT_NAME=${{ steps.cf-setup.outputs.target-environment }}
          --strategy rolling

      - name: Create or update proxy u-p service
        run: |
          props='{"proxy_url": "https://outbound-proxy-${{ steps.cf-setup.outputs.target-environment }}.apps.internal:61443", "proxy_url_no_tls" : "http://outbound-proxy-${{ steps.cf-setup.outputs.target-environment }}.apps.internal:8080"}'

          cf target -s ${{ steps.cf-setup.outputs.target-environment }}
          cf create-user-provided-service outbound-proxy -p "$props" || cf update-user-provided-service outbound-proxy -p "$props"
          cf target -s ${{ steps.cf-setup.outputs.target-environment }}-closed
          cf create-user-provided-service outbound-proxy -p "$props" || cf update-user-provided-service outbound-proxy -p "$props"
          cf target -s ${{ steps.cf-setup.outputs.target-environment }}-warpgate
          cf create-user-provided-service outbound-proxy -p "$props" || cf update-user-provided-service outbound-proxy -p "$props"
